### ISSUE TITLE
RuntimeError: inputs must be on unique devices when python main.py

### ISSUE THREAD

**Issue by sunset326** [dddzg/MoCo#3]
hi,when i reimplement moco,
and carry out python main.py,
an error occured,as described:

Traceback (most recent call last):
  File "main.py", line 174, in <module>
    ret, queue = train(train_dataloader, model_q, model_k, queue, optimizer, config.DEVICE)
  File "main.py", line 117, in train
    k = model_k(img_k)  # N x C
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 154, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 87, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 70, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 21, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/anaconda2/envs/Maskrcnn_Benchmark/lib/python3.6/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: inputs must be on unique devices

Wish your reply! thx.

**Comment by sunset326** [comment]
i have solved this bug,in the main.py 49 row,
device_list = [config.GPU_ID]  * 4 # Shuffle BN can be applied through there is only one gpu.
here using 4gpus,so i delete '*4',then it works.
thank you making the code public to let me have a chance to learn.
